export const CART_UPDATE_ITEM_REQUEST = "CART_UPDATE_ITEM_REQUEST";
export const CART_UPDATE_ITEM_SUCCESS = "CART_UPDATE_ITEM_SUCCESS";
export const CART_UPDATE_ITEM_FAIL = "CART_UPDATE_ITEM_FAIL";
export const CART_UPDATE_ITEM_RESET = "CART_UPDATE_ITEM_RESET";
