export const PRODUCT_STOCK_UPDATE_REQUEST = "PRODUCT_STOCK_UPDATE_REQUEST";
export const PRODUCT_STOCK_UPDATE_SUCCESS = "PRODUCT_STOCK_UPDATE_SUCCESS";
export const PRODUCT_STOCK_UPDATE_FAIL = "PRODUCT_STOCK_UPDATE_FAIL";
export const PRODUCT_STOCK_UPDATE_RESET = "PRODUCT_STOCK_UPDATE_RESET";
