export const ADD_SHIPPING_ADDRESS_REQUEST = "ADD_SHIPPING_ADDRESS_REQUEST";
export const ADD_SHIPPING_ADDRESS_SUCCESS = "ADD_SHIPPING_ADDRESS_SUCCESS";
export const ADD_SHIPPING_ADDRESS_FAIL = "ADD_SHIPPING_ADDRESS_FAIL";
export const ADD_SHIPPING_ADDRESS_RESET = "ADD_SHIPPING_ADDRESS_RESET";
