export const UPDATE_PAYMENT_METHOD_REQUEST = "UPDATE_PAYMENT_METHOD_REQUEST";
export const UPDATE_PAYMENT_METHOD_SUCCESS = "UPDATE_PAYMENT_METHOD_SUCCESS";
export const UPDATE_PAYMENT_METHOD_FAIL = "UPDATE_PAYMENT_METHOD_FAIL";
export const UPDATE_PAYMENT_METHOD_RESET = "UPDATE_PAYMENT_METHOD_RESET";
